# Generated by Django 4.0.6 on 2022-07-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='False', max_length=30)),
                ('age', models.PositiveIntegerField(blank='False', null='False')),
            ],
        ),
    ]
